apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chiefadmin-monitor
subjects:
  - kind: ServiceAccount    
    name: chief-admin
    namespace: default # required
roleRef:
  kind: ClusterRole          
  name: monitor  
  apiGroup: rbac.authorization.k8s.io