---
  - name: Gather Facts Test
    hosts: all
    gather_facts: no
    become: yes
  
    tasks:
      - name: Update the package manager cache.
        ansible.builtin.apt:
          update_cache: yes
      - name: Install the Apache web server package (`apache2`).
        ansible.builtin.apt:
          name: apache2
      - name: Enable and start the Apache service.
        ansible.builtin.service:
          name: apache2
          state: started
      - name: Deploy a simple 'index.html' file
        ansible.builtin.copy:
          src: ./index.html
          dest: /var/www/html
          owner: www-data
          group: www-data
          mode: 0644
      