AWSTemplateFormatVersion: 2010-09-09
Description: DevOps Solution

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Tags:
      - Key: Name
        Value: MyInternetGateway
  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway
  MyPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: "10.0.1.0/24"
      VpcId: !Ref MyVPC
      AvailabilityZone: us-west-2a
      Tags:
        - Key: "Name"
          Value: "MyPrivateSubnet"
  MyPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: "10.0.2.0/24"
      VpcId: !Ref MyVPC
      AvailabilityZone: us-west-2a
      MapPublicIpOnLaunch: "true"
      Tags:
        - Key: "Name"
          Value: "MyPublicSubnet"
  MyPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
  MyPublicRoute:
    Type: AWS::EC2::Route
    Properties:
      VpcId: !