apiVersion: v1
kind: Namespace
metadata:
  name: cyberco
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-db
  namespace: cyberco
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis 
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:buster
        ports:
        - containerPort: 6379